spring:
  application:
    name: Cloud-BBQ


server:
  port: 8492



  datasource:
    url: jdbc:h2:mem:gignetic_db  # 'mem' creates a temporary database in RAM
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true            # Enables the browser-based DB GUI
      path: /h2-console        # Access at http://localhost:8080/h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update         # Automatically creates tables based on your Entities
    show-sql: true             # Prints SQL to the console

  # Jackson JSON Configuration
  jackson:
    serialization:
      fail-on-empty-beans: false
